# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /seckill

spring:
  # ThymeleafProperties
  thymeleaf:
    cache: false
  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: root
    hikari:
      pool-name: DataHikariPool
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 1800000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
  # RedisProperties
  redis:
    host: 10.211.55.4
    port: 6379
    password: 999
    database: 12
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 0

# MyBatisPlusProperties
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.concurrency.seckill.entity

# LoggingProperties
logging:
  level:
    com.concurrency.seckill.mapper: debug
